In [1]:
### Python for algo trading

In [2]:
def twice(num):
    return num*2

In [4]:
twice(10)

20

In [5]:
## twice() is equvivalent to: 
lambda num: num*2

<function __main__.<lambda>(num)>

In [7]:
seq = [1,2,3,4,5]

In [9]:
list(map(twice, seq))

[2, 4, 6, 8, 10]

In [10]:
# This can also be written as:
list(map(lambda num: num*2, seq))

[2, 4, 6, 8, 10]

In [14]:
list(filter(lambda num: num%2 == 0, seq))

[2, 4]

In [15]:
l = [1,2,3,5,3,2,3,4,3,2,1]

In [20]:
print(l.pop())

3


In [21]:
l

[1, 2, 3, 5, 3, 2]

In [1]:
import numpy as np

In [2]:
list1 = [1,2,3]

In [3]:
np.array(list1)

array([1, 2, 3])

In [7]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.zeros(((5,5,5)))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [15]:
# linspace is linearly spaced
np.linspace(1,10,30)

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [16]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5,5)

array([[0.75826603, 0.90097831, 0.49774939, 0.88470884, 0.7301246 ],
       [0.52001895, 0.15087184, 0.70952426, 0.16666273, 0.0974035 ],
       [0.40354063, 0.1660631 , 0.35678265, 0.2998072 , 0.8061718 ],
       [0.79285213, 0.67122791, 0.68192221, 0.52278264, 0.53710364],
       [0.68070723, 0.34799024, 0.42204828, 0.33388706, 0.47677618]])

In [23]:
np.random.randn(5,5)

array([[-0.03036357, -1.21481458,  1.03710333, -0.29187814,  1.73820295],
       [ 1.00009395, -0.32831084, -0.50152397,  0.28175361, -1.42559504],
       [-0.05425643,  0.86700428, -0.04256829,  0.68992928,  0.44946473],
       [-0.71199083, -1.1575899 , -0.08073277,  0.86379249, -1.43311709],
       [ 0.1731004 , -0.76816243,  0.42430567,  0.1419146 ,  1.70712469]])

In [27]:
ranarr = np.random.randint(1,100,10)

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr.shape

(25,)

In [33]:
arr.reshape(5,5).shape

(5, 5)

In [35]:
arr.dtype

dtype('int64')

In [37]:
ranarr.max()

98

In [38]:
ranarr.min()

16

In [39]:
ranarr.argmax()

6

In [40]:
ar = np.arange(10)

In [41]:
ar + ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
ar *  ar

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [44]:
ar - ar

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
ar/ar

/home/naiph/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [46]:
np.sqrt(ar)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [47]:
np.exp(ar)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [48]:
np.log(ar)

/home/naiph/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [49]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
ar[1:5]

array([1, 2, 3, 4])

In [51]:
ar[1:5] = 10

In [52]:
ar

array([ 0, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [54]:
ar_copy = ar.copy()

In [55]:
ar_copy[0:8] = 69

In [57]:
ar_copy

array([69, 69, 69, 69, 69, 69, 69, 69,  8,  9])

In [69]:
ar2 = np.arange(5,50,5)

In [73]:
ar2 = ar2.reshape(3,3)

In [74]:
ar2[2]

array([35, 40, 45])

In [75]:
ar2[2][2]

45

In [77]:
ar1 = np.arange(10)

In [78]:
ar1 > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [79]:
boolar = ar1 > 4 

In [80]:
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
ar1[boolar]

array([5, 6, 7, 8, 9])

In [82]:
# this is same as
ar1[ar1>4]

array([5, 6, 7, 8, 9])